import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  UserOutline,
  LockOutline,
  SettingOutline,
  PlusOutline,
  DeleteOutline,
  CheckCircleTwoTone,
  LockTwoTone,
  MinusSquareOutline,
  PlusSquareOutline,
  PlusCircleOutline,
  StarTwoTone,
  MenuOutline,
  GoogleOutline,
  AppstoreOutline,
  WarningOutline,
  ShopOutline,
  UploadOutline,
  CloudUploadOutline,
  ReloadOutline,
  MoneyCollectOutline,
  ExportOutline,
  CommentOutline,
  BellOutline,
  BellTwoTone,
  ProjectOutline,
  FileSearchOutline,
  SelectOutline,
  EyeInvisibleOutline,
  LogoutOutline,
  ToolOutline,
  ToolTwoTone,
  CodeSandboxOutline,
  ProfileOutline,
  CopyOutline,
  CopyTwoTone,
  TagsOutline,
  GlobalOutline,
  CopyrightOutline,
  LinkOutline,
  EyeOutline,
  CloudDownloadOutline,
  ManOutline,
  WomanOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  UserOutline,
  LockOutline,
  SettingOutline,
  PlusOutline,
  DeleteOutline,
  CheckCircleTwoTone,
  LockTwoTone,
  MinusSquareOutline,
  PlusSquareOutline,
  PlusCircleOutline,
  StarTwoTone,
  MenuOutline,
  GoogleOutline,
  AppstoreOutline,
  WarningOutline,
  ShopOutline,
  UploadOutline,
  CloudUploadOutline,
  ReloadOutline,
  MoneyCollectOutline,
  ExportOutline,
  CommentOutline,
  BellOutline,
  BellTwoTone,
  ProjectOutline,
  FileSearchOutline,
  SelectOutline,
  EyeInvisibleOutline,
  LogoutOutline,
  ToolOutline,
  CodeSandboxOutline,
  ToolTwoTone,
  ProfileOutline,
  CopyOutline,
  CopyTwoTone,
  TagsOutline,
  GlobalOutline,
  CopyrightOutline,
  LinkOutline,
  EyeOutline,
  CloudDownloadOutline,
  ManOutline,
  WomanOutline,
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
