- hosts: localhost
  tasks:
    - name: build kgteacher
      command: "{{item}}"
      with_items:
        - git checkout master
        - ng build --configuration production
      args:
        chdir: "{{playbook_dir}}/.."
- hosts: ykwell.cn
  user: ubuntu
  tasks:
    - name: deploy kgteacher
      synchronize:
        src: "{{playbook_dir}}/../dist/kgteacher/"
        dest: /var/www/ykgk/kgteacher/
        #rsync_opts:
        #  - "--exclude=assets/"
